ApeSwapFinance/apeswap-api

src/stats/stats.controller.ts
src/stats/stats.service.ts
src/stats/subgraph.service.spec.ts
src/stats/subgraph.service.ts
src/stats/utils/subgraph.queries.ts

Implementation to provide data for defistation:
https://github.com/cosmostation/defistation-web/blob/master/data-provider-api.md

Defistation data provider implementation

---

src/utils/incentivizedPools.ts

Added xbtc to incentivizedPools.ts

feat: Added xbtc pool to api

---

src/utils/incentivizedPools.ts

Updated the reward per block and the end block on the BANANA --> LYPTUS staking pool

feat: Updated LYPTUS incentivized pool

---

src/utils/incentivizedPools.ts

Added GNANA --> KEYFI pool to incentivizedPools

feat: Added keyfi pool

---

src/utils/incentivizedPools.ts

API update for BANANA -> BFT staking pool on incentivizedPools.ts

feat: Added BANANA -> BFT staking pool

---

src/utils/incentivizedPools.ts

feat: Added nrv pool

---

src/nfas/nfas-tracking.service.ts
src/utils/incentivizedPools.ts

Feat: nrv pool to main

---

src/utils/incentivizedPools.ts

feat: Added incentivized moonlight pool

feat: Added incentivized moonlight pool

---

src/lottery/drawing.service.ts

feat: Moonlight to incentivized pools

feat: Moonlight to incentivized pools

---

src/stats/stats.service.ts

Reverts ApeSwapFinance/apeswap-api#73

Revert "feature/pools_strapi"

---

src/utils/incentivizedPools.ts

feat: Added TAPE pool

---

src/lottery/drawing.service.ts
src/utils/incentivizedPools.ts

Tape pool in production

---

src/utils/incentivizedPools.ts

feat: Added bog

---

src/utils/incentivizedPools.ts

BOG to prod

---

src/utils/incentivizedPools.ts

hifi pool fix

---

src/utils/incentivizedPools.ts

hotfix updated reward HIFI token

hotfix updated reward HIFI token

---

src/utils/incentivizedPools.ts

updated end block for gnana-banana pool

updated end block for gnana-banana pool

---

src/nfas/nfas-auction.service.ts
src/nfas/nfas-tracking.service.ts
src/nfas/nfas.controller.ts
src/nfas/nfas.module.ts

chore: Add cache to get NFA bids

---

src/utils/incentivizedPools.ts

Extension of the GNANA - BANANA pool

Update GNANA - BANANA pool rewards

---

src/iazo/dto/iazo.dto.ts
src/iazo/iazo.service.ts
src/iazo/schema/iazo.schema.ts

I removed uneeded parameters and instead of throwing when verification fails I just save the result.

refactor: Always save SS-IAO
